spring.profiles.active: log-debug, products-from-api

info:
  app:
    name: ${name}
    version: ${version}

server:
  port: 8080

logging.file: logs/jl-products.log
logging:
    max-size: 5MB
    max-history: 5

management:
  endpoints:
    web:
      exposure:
        include: info, health, mappings, logfile
      base-path: /monitor
  endpoint:
    health:
      show-details: always

---

spring:
  profiles: products-from-file
feature:
  toggles:
    productsFromApi: false
products:
  resource:
    filename: data/actual-products.json

---

spring:
  profiles: products-from-api
feature:
  toggles:
    productsFromApi: true
products:
  resource:
    url: "https://jl-nonprod-syst.apigee.net/v1/categories/CATEGORY_ID/products?key=2ALHCAAs6ikGRBoy6eTHA58RaG097Fma"

---

spring:
  profiles: log-info
logging:
  level:
    root: warn
    org.springframework: warn
    app.tapme: info

---

spring:
  profiles: log-debug
logging:
  level:
    root: info
    org.springframework: info
    dlc.jl: debug
